# Generated by Django 4.2.17 on 2025-01-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedpost',
            name='nearest_town',
        ),
        migrations.RemoveField(
            model_name='post',
            name='nearest_town',
        ),
    ]
