# Generated by Django 4.2.17 on 2025-01-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_religiousorder_post_religious_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='location',
        ),
        migrations.AddField(
            model_name='post',
            name='county',
            field=models.CharField(default='Unknown', max_length=200),
        ),
        migrations.AddField(
            model_name='post',
            name='nearest_town',
            field=models.CharField(default='Unknown', max_length=200),
        ),
    ]
