# Generated by Django 4.2.17 on 2025-01-26 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_approvedpost_nearest_town_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approvedpost',
            name='religious_order',
        ),
        migrations.RemoveField(
            model_name='post',
            name='religious_order',
        ),
    ]
