# Generated by Django 4.2.17 on 2025-01-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_post_latitude_remove_post_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Pending Approval'), (2, 'Published')], default=0),
        ),
    ]
