# Generated by Django 4.2.17 on 2025-01-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_holding'),
    ]

    operations = [
        migrations.AddField(
            model_name='holding',
            name='coordinates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
