# Generated by Django 4.2.17 on 2025-01-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_holding_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='nearest_town',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
