# Generated by Django 5.1.5 on 2025-04-26 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deanery_name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'deaneries',
            },
        ),
        migrations.CreateModel(
            name='HouseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(choices=[(1, 'Abbey'), (2, 'Priory'), (3, 'Nunnery')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ReligiousOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_order', models.IntegerField(choices=[(1, 'Augustinian'), (2, 'Benedictine'), (3, 'Carthusian'), (4, 'Cistercian'), (5, 'Cluniac'), (6, 'Dominican'), (7, 'Franciscan'), (8, 'Gilbertine'), (9, 'Knights Hospitaller'), (10, 'Premonstratensian'), (11, 'Trinitarian')])),
            ],
        ),
        migrations.CreateModel(
            name='ValorRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True)),
                ('record_type', models.CharField(choices=[('Monastery', 'Monastery'), ('Collegiate', 'Collegiate'), ('Rectory', 'Rectory')], max_length=50)),
                ('dedication', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('source_ref_vol', models.IntegerField(blank=True, null=True)),
                ('source_ref_page', models.IntegerField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valor_records', to=settings.AUTH_USER_MODEL)),
                ('deanery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valor_records.deanery')),
                ('house_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_records', to='valor_records.housetype')),
                ('last_edited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_valor_records', to=settings.AUTH_USER_MODEL)),
                ('religious_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='religious_order_records', to='valor_records.religiousorder')),
            ],
        ),
        migrations.CreateModel(
            name='ValorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translation', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valor_texts', to=settings.AUTH_USER_MODEL)),
                ('valor_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='valor_records.valorrecord')),
            ],
        ),
    ]
