# Generated by Django 5.1.5 on 2025-02-28 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Institution',
            new_name='ValorRecord',
        ),
        migrations.AlterModelOptions(
            name='deanery',
            options={'verbose_name_plural': 'deaneries'},
        ),
        migrations.RenameField(
            model_name='housetype',
            old_name='institution',
            new_name='valor_record',
        ),
    ]
