# Generated by Django 5.1.5 on 2025-02-28 18:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0002_rename_institution_valorrecord_alter_deanery_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='valorrecord',
            old_name='type',
            new_name='record_type',
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valor_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='house_type',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valor_records.housetype'),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_valor_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
