# Generated by Django 5.1.5 on 2025-03-01 00:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0003_rename_type_valorrecord_record_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorrecord',
            name='house_type',
        ),
        migrations.AlterField(
            model_name='housetype',
            name='valor_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='valor_records.valorrecord'),
        ),
    ]
