# Generated by Django 5.1.5 on 2025-03-01 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0004_remove_valorrecord_house_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='valor_record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='valor_records.valorrecord'),
        ),
    ]
