# Generated by Django 5.1.5 on 2025-03-06 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0005_alter_housetype_valor_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorrecord',
            name='record_type',
            field=models.CharField(choices=[('Monastery', 'Monastery'), ('Collegiate', 'Collegiate'), ('Rectory', 'Rectory')], max_length=50),
        ),
    ]
