# Generated by Django 5.1.5 on 2025-03-07 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0007_auto_20250306_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReligiousOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('religious_order', models.IntegerField(choices=[(1, 'Augustinian'), (2, 'Benedictine'), (3, 'Carthusian'), (4, 'Cistercian'), (5, 'Cluniac'), (6, 'Dominican'), (7, 'Franciscan'), (8, 'Gilbertine'), (9, 'Knights Hospitaller'), (10, 'Premonstratensian'), (11, 'Trinitarian')])),
                ('valor_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='valor_records.valorrecord')),
            ],
        ),
    ]
