# Generated by Django 5.1.5 on 2025-03-07 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0008_religiousorder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='housetype',
            name='valor_record',
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='house_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='valor_records.housetype'),
        ),
        migrations.AlterField(
            model_name='housetype',
            name='house_type',
            field=models.CharField(choices=[(1, 'Abbey'), (2, 'Priory'), (3, 'Nunnery')], max_length=50),
        ),
    ]
