# Generated by Django 5.1.5 on 2025-03-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0009_remove_housetype_valor_record_valorrecord_house_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='house_type',
            field=models.CharField(choices=[(1, 'Abbey'), (2, 'Priory'), (3, 'Nunnery')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='religiousorder',
            name='valor_record',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='religious_order', to='valor_records.valorrecord'),
        ),
    ]
