# Generated by Django 5.1.5 on 2025-03-07 03:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0011_alter_housetype_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorrecord',
            name='house_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valor_records', to='valor_records.housetype'),
        ),
    ]
