# Generated by Django 5.1.5 on 2025-03-07 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0012_alter_valorrecord_house_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='housetype',
            name='house_type',
            field=models.CharField(choices=[(1, 'Abbey'), (2, 'Priory'), (3, 'Nunnery')], max_length=50, unique=True),
        ),
    ]
