# Generated by Django 5.1.5 on 2025-03-07 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0015_populate_house_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='religiousorder',
            name='valor_record',
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='religious_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='religious_order_records', to='valor_records.religiousorder'),
        ),
        migrations.AlterField(
            model_name='valorrecord',
            name='house_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house_records', to='valor_records.housetype'),
        ),
    ]
