# Generated by Django 5.1.5 on 2025-03-09 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0017_populate_religious_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorrecord',
            name='source_ref_page',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='source_ref_vol',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
