# Generated by Django 5.1.5 on 2025-03-10 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0018_valorrecord_source_ref_page_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorrecord',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
