# Generated by Django 5.1.5 on 2025-03-11 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0019_valorrecord_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorrecord',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
