# Generated by Django 5.1.5 on 2025-03-20 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0020_valorrecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorrecord',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
