# Generated by Django 5.1.5 on 2025-03-23 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0021_alter_valorrecord_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValorText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.TextField()),
                ('translation', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_valor_texts', to=settings.AUTH_USER_MODEL)),
                ('valor_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='texts', to='valor_records.valorrecord')),
            ],
        ),
    ]
