# Generated by Django 5.1.5 on 2025-03-24 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valor_records', '0022_valortext'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorrecord',
            name='dedication',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
