# Generated by Django 5.1.5 on 2025-02-11 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorrecord',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
