# Generated by Django 5.1.5 on 2025-02-12 00:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0002_valorrecord_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorrecord',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='slug',
            field=models.SlugField(default='default-slug', unique=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
