# Generated by Django 5.1.5 on 2025-02-12 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0003_valorrecord_created_at_valorrecord_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archdeaconry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Diocese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='record_type',
            field=models.CharField(choices=[('Parish', 'Parish'), ('Religious House', 'Religious House'), ('College', 'College')], default='Parish', max_length=50),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='archdeaconry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.archdeaconry'),
        ),
        migrations.CreateModel(
            name='Deanery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('archdeaconry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.archdeaconry')),
            ],
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='deanery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.deanery'),
        ),
        migrations.AddField(
            model_name='archdeaconry',
            name='diocese',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.diocese'),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='diocese',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.diocese'),
        ),
        migrations.AddField(
            model_name='diocese',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.province'),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.province'),
        ),
    ]
