# Generated by Django 5.1.5 on 2025-02-12 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0004_archdeaconry_diocese_province_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='valorrecord',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
