# Generated by Django 5.1.5 on 2025-02-13 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0006_alter_archdeaconry_name_alter_deanery_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('deanery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='records.deanery')),
            ],
        ),
    ]
