# Generated by Django 5.1.5 on 2025-02-13 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0007_parish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='archdeaconry',
            options={'verbose_name_plural': 'Archdeaconries'},
        ),
        migrations.AlterModelOptions(
            name='deanery',
            options={'verbose_name_plural': 'Deaneries'},
        ),
        migrations.AlterModelOptions(
            name='parish',
            options={'verbose_name_plural': 'Parishes'},
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='parish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.parish'),
        ),
    ]
