# Generated by Django 5.1.5 on 2025-02-13 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0008_alter_archdeaconry_options_alter_deanery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='valorrecord',
            name='abbot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='house_type',
            field=models.CharField(blank=True, choices=[('Abbey', 'Abbey'), ('Priory', 'Priory'), ('Convent', 'Convent'), ('Friary', 'Friary')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='monastery_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='pence',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='pounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='religious_order',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='shillings',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='valorrecord',
            name='record_type',
            field=models.CharField(choices=[('Monastery', 'Monastery'), ('College', 'College'), ('Rectory', 'Rectory')], default='Monastery', max_length=50),
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('pounds', models.IntegerField(blank=True, null=True)),
                ('shillings', models.IntegerField(blank=True, null=True)),
                ('pence', models.IntegerField(blank=True, null=True)),
                ('valor_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='records.valorrecord')),
            ],
        ),
    ]
