# Generated by Django 5.1.5 on 2025-02-13 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0009_valorrecord_abbot_valorrecord_house_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monastery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_type', models.CharField(blank=True, choices=[('Abbey', 'Abbey'), ('Priory', 'Priory'), ('Convent', 'Convent'), ('Friary', 'Friary')], max_length=50, null=True)),
                ('religious_order', models.CharField(blank=True, choices=[('Benedictines', 'Benedictines'), ('Cistercians', 'Cistercians'), ('Franciscans', 'Franciscans'), ('Dominicans', 'Dominicans')], max_length=50, null=True)),
                ('monastery_name', models.CharField(blank=True, max_length=255, null=True)),
                ('abbot', models.CharField(blank=True, max_length=255, null=True)),
                ('pounds', models.IntegerField(blank=True, null=True)),
                ('shillings', models.IntegerField(blank=True, null=True)),
                ('pence', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='valorrecord',
            name='monastery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='records.monastery'),
        ),
    ]
