# Generated by Django 5.1.5 on 2025-02-13 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0010_monastery_valorrecord_monastery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monastery',
            name='pence',
        ),
        migrations.RemoveField(
            model_name='monastery',
            name='pounds',
        ),
        migrations.RemoveField(
            model_name='monastery',
            name='shillings',
        ),
    ]
