# Generated by Django 5.1.5 on 2025-02-13 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0011_remove_monastery_pence_remove_monastery_pounds_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='valorrecord',
            name='abbot',
        ),
        migrations.RemoveField(
            model_name='valorrecord',
            name='house_type',
        ),
        migrations.RemoveField(
            model_name='valorrecord',
            name='monastery_name',
        ),
        migrations.RemoveField(
            model_name='valorrecord',
            name='pence',
        ),
        migrations.RemoveField(
            model_name='valorrecord',
            name='pounds',
        ),
        migrations.RemoveField(
            model_name='valorrecord',
            name='religious_order',
        ),
        migrations.RemoveField(
            model_name='valorrecord',
            name='shillings',
        ),
    ]
