# Generated by Django 5.1.5 on 2025-02-25 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0013_valorrecord_creator_username_valorrecord_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monastery',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='monastery',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
