# Generated by Django 5.1.5 on 2025-02-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0014_monastery_latitude_monastery_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monastery',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='monastery',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
