# Generated by Django 5.1.5 on 2025-02-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('records', '0015_alter_monastery_latitude_alter_monastery_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='monastery',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
